---
title: "Sample Rasters"
author: "Peter Dudley"
date: "9/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
# Sample Rasters onto the Grid

This script takes the grid and samples a raster flow stack with it 
```{r}
#____________________________________________________________________#
##### Options #####
# Grid file location
grid_file_resolution = 20
# What is the buffer distance of the grid
max_buffer = 500
# Set the desired EPGS code for the GIS files
EPSG = 32610
# Location of rasters
raster_folder = "../../../data/GIS/depth_rasters_large/"
# Location of grid
grid_folder = "../../../temporary/R/"
# Where to save the output
output_folder = "../../../temporary/NetLogo/"
# A vector of the flow values for the input rasters 
flows = c(75, 150, 300, 500, 700, 1000, 1300, 1600, 2000, 3000, 4000)
flows = c(75, 300)
#____________________________________________________________________#
```

Load the necessary libraries 
```{r, message=FALSE, warning=FALSE}
# the simple features library for most of the shape file stuff
library(sf)
# leaflet for plotting shape files
library(leaflet)
# you know why
library(tidyverse)
# deal with most of the rater calculations
library(raster)
# to smooth the center line of the river
library(smoothr)
# the viridis color map
library(viridis)
# a faster way to do raster sampling with shape files
library(exactextractr)

# Make sure the area function is raster::area 
area = raster::area

# load the functions for this script
source("./scripts/Sample_Raster_Functions.R")
```

Load in the files.
```{r}
river_grid = readRDS(paste0("../River_Linear/pass/river_grid_", grid_file_resolution, "_", max_buffer, ".rds"))
```

Put all the rasters in a stack. 
```{r}
raster_stack = load_rasters(type = "depth",
                            folder = raster_folder,
                            flows = flows,
                            EPGS = EPGS)
```

Now sample them onto the grid. The sampling also takes the terrain slope function to calculate the bottom area.
```{r}
sampeled_grid = sample_grid(stack = raster_stack,
                           grid = river_grid,
                           type = "depth")
```

Plot one of the depths
```{r fig.height=10, fig.width=3, fig.align = 'center'}
g = ggplot(sampeled_grid, aes(x = x , y = y , fill = mean.D300 )) +
  theme_classic() +
  geom_raster(na.rm = TRUE)
g
```

Plot the difference between the bottom area and area
```{r fig.height=10, fig.width=3, fig.align = 'center'}
stats_plot = sampeled_grid %>% 
  mutate(difference = ifelse((bottom_area-area) == 0, NA, (bottom_area-area)))

g = ggplot(stats_plot, aes(x = x , y = y , fill = (difference) )) +
  theme_classic() +
  geom_raster(na.rm = T)
g
```
